const KEY='securityPerformanceJD_v2';
const pillars=[
{name:'Gestão dos KPIs Operacionais',weight:.30,items:[['Turnover','Gestão do turnover, análise de causas e ações preventivas'],['Absenteísmo','Controle, análise de causas e redução do absenteísmo'],['Horas extras','Planejamento de cobertura e reposição de faltas'],['Postos descobertos','Prevenção de gaps e rápida recomposição operacional']]},
{name:'Desenvolvimento da Liderança',weight:.20,items:[['Postura','Postura profissional dos Vigilantes Líderes'],['Gestão de equipe','Liderança, delegação e acompanhamento'],['Treinamentos','Trilhas de treinamento para líderes e equipe'],['Comunicação','DDS, reuniões, feedbacks e comunicação assertiva'],['Formação de novos líderes','Preparação de profissionais para liderança']]},
{name:'Qualidade Operacional e Segurança',weight:.20,items:[['Procedimentos John Deere','Cumprimento dos procedimentos de segurança'],['Auditorias e não conformidades','Resultado de auditorias no cliente'],['Gestão de ocorrências','Análise, resposta, prevenção e registro'],['Inspeções e vulnerabilidades','Identificação antecipada de riscos']]},
{name:'Inovação e Melhoria Contínua',weight:.15,items:[['Iniciativas de inovação','Soluções para segurança e negócio'],['Resultados das iniciativas','Ganho de eficiência, redução de risco ou custo']]},
{name:'Gestão do Cliente e Compliance',weight:.15,items:[['Processos OEA','Cumprimento e evolução dos processos OEA'],['Relacionamento com cliente','Gestão de demandas e confiança'],['Compliance e governança','Aderência às regras, registros e controles']]}
];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{coordinators:[],evaluations:[],pdi:[]}}catch{return{coordinators:[],evaluations:[],pdi:[]}}}
let db=load();
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function classification(n){if(n>=4.5)return['Excepcional','green'];if(n>=4)return['Acima do esperado','green'];if(n>=3)return['Dentro do esperado','yellow'];if(n>=2)return['Necessita desenvolvimento','red'];return['Performance crítica','red']}
function save(){localStorage.setItem(KEY,JSON.stringify(db));renderAll()}
function go(view){const target=$('#view-'+view);if(!target)return;$$('.view').forEach(v=>v.classList.remove('active-view'));target.classList.add('active-view');$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const titles={dashboard:'Dashboard Executivo',avaliacao:'Avaliação 180°',ranking:'Ranking',pdi:'Plano de Desenvolvimento Individual',coordenadores:'Coordenadores',config:'Configurações'};$('#pageTitle').textContent=titles[view]||'Gestão de Performance';if(innerWidth<700)$('#sidebar').classList.remove('open');if(view==='avaliacao')renderCriteria();renderAll()}
function initNav(){$$('.nav-item').forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));$('#menuBtn')?.addEventListener('click',()=>$('#sidebar').classList.toggle('open'));$('#exportBtn')?.addEventListener('click',exportData);$('#clearFilters')?.addEventListener('click',()=>{$('#dashPeriod').value='all';$('#dashUnit').value='all';renderDashboard()});$('#rankingSearch')?.addEventListener('input',renderRanking);$('#rankingPeriod')?.addEventListener('change',renderRanking);$('#dashPeriod')?.addEventListener('change',renderDashboard);$('#dashUnit')?.addEventListener('change',renderDashboard);$('#addCoordinatorBtn')?.addEventListener('click',newCoordinator);$('#addPdiBtn')?.addEventListener('click',newPdi);$('#modalClose')?.addEventListener('click',closeModal);$('#modal')?.addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});$('#evaluationForm')?.addEventListener('submit',submitEvaluation)}
function renderCriteria(){const box=$('#criteriaContainer');if(!box)return;let html='';pillars.forEach((p,pi)=>{html+=`<div class="criteria-group"><div class="criteria-title"><strong>${p.name}</strong><span>Peso ${p.weight*100}% • notas 1 a 5</span></div>`;p.items.forEach((it,ii)=>{html+=`<div class="criterion"><div class="criterion-name"><b>${it[0]}</b><span>${it[1]}</span></div><input required min="1" max="5" step="0.1" type="number" name="score_${pi}_${ii}" placeholder="Nota"><textarea name="obs_${pi}_${ii}" placeholder="Evidência / observação"></textarea></div>`});html+='</div>'});box.innerHTML=html}
function renderCoordinatorSelect(){const s=$('#evalCoordinator');if(!s)return;const old=s.value;s.innerHTML='<option value="">Selecione...</option>'+db.coordinators.map(c=>`<option value="${esc(c.id)}">${esc(c.name)} — ${esc(c.unit)}</option>`).join('');if(db.coordinators.some(c=>c.id===old))s.value=old;s.onchange=()=>{const c=db.coordinators.find(x=>x.id===s.value);if(c)$('#evalUnit').value=c.unit}}
function renderFilters(){const periods=[...new Set(db.evaluations.map(e=>e.period).filter(Boolean))].sort().reverse(),units=[...new Set(db.evaluations.map(e=>e.unit).filter(Boolean))].sort();['dashPeriod','rankingPeriod'].forEach(id=>{const el=$('#'+id);if(!el)return;const old=el.value;el.innerHTML='<option value="all">Todos os períodos</option>'+periods.map(p=>`<option value="${esc(p)}">${esc(p)}</option>`).join('');el.value=periods.includes(old)?old:'all'});const du=$('#dashUnit');if(du){const old=du.value;du.innerHTML='<option value="all">Todas as unidades</option>'+units.map(u=>`<option value="${esc(u)}">${esc(u)}</option>`).join('');du.value=units.includes(old)?old:'all'}}
function filtered(){const p=$('#dashPeriod')?.value||'all',u=$('#dashUnit')?.value||'all';return db.evaluations.filter(e=>(p==='all'||e.period===p)&&(u==='all'||e.unit===u))}
function renderDashboard(){const ev=filtered(),avg=ev.length?ev.reduce((a,e)=>a+Number(e.final),0)/ev.length:null;$('#kpiCoordinators').textContent=db.coordinators.length;$('#kpiEvaluations').textContent=ev.length;$('#kpiAverage').textContent=avg!==null?avg.toFixed(2):'—';const done=db.pdi.length?db.pdi.filter(x=>x.status==='Concluído').length/db.pdi.length:0;$('#kpiPdi').textContent=Math.round(done*100)+'%';const counts={'Excepcional':0,'Acima do esperado':0,'Dentro do esperado':0,'Necessita desenvolvimento':0,'Performance crítica':0};ev.forEach(e=>{if(counts[e.classification]!==undefined)counts[e.classification]++});const max=Math.max(1,...Object.values(counts));$('#distribution').innerHTML=Object.entries(counts).map(([k,v])=>`<div class="dist-row"><span>${k}</span><div class="bar"><i style="width:${v/max*100}%"></i></div><b>${v}</b></div>`).join('');const ranked=[...ev].sort((a,b)=>b.final-a.final).slice(0,5);$('#topRanking').innerHTML=ranked.length?ranked.map((e,i)=>`<div class="rank-row"><span class="rank-num">${i+1}</span><div class="rank-name"><b>${esc(e.coordinator)}</b><span>${esc(e.unit)} • ${esc(e.period)}</span></div><span class="score">${Number(e.final).toFixed(2)}</span></div>`).join(''):'<div class="empty-chart">Nenhuma avaliação cadastrada.</div>';const low=[...ev].sort((a,b)=>a.final-b.final).slice(0,4);$('#attention').innerHTML=low.length?low.map(e=>{const[c,cl]=classification(e.final);return`<div class="attention-row"><span>${esc(e.coordinator)}<br><small>${esc(e.unit)}</small></span><span class="badge ${cl}">${Number(e.final).toFixed(2)} • ${c}</span></div>`}).join(''):'<div class="empty-chart">Sem pontos de atenção.</div>';drawChart(ev)}
function drawChart(ev){const c=$('#evolutionChart');if(!c)return;const ctx=c.getContext('2d'),w=c.clientWidth||500,h=220,d=devicePixelRatio||1;c.width=w*d;c.height=h*d;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);const groups={};ev.forEach(e=>(groups[e.period]??=[]).push(Number(e.final)));const labels=Object.keys(groups).sort(),vals=labels.map(k=>groups[k].reduce((a,b)=>a+b,0)/groups[k].length);$('#emptyChart').style.display=labels.length?'none':'grid';if(!labels.length)return;ctx.strokeStyle='#e6ebf2';ctx.lineWidth=1;for(let y=1;y<=5;y++){const yy=h-25-(y-1)*(h-50)/4;ctx.beginPath();ctx.moveTo(35,yy);ctx.lineTo(w-15,yy);ctx.stroke();ctx.fillStyle='#8a95a6';ctx.font='9px Inter';ctx.fillText(y,15,yy+3)}const xf=i=>45+i*(labels.length===1?1:(w-70)/(labels.length-1));ctx.strokeStyle='#1769e0';ctx.lineWidth=3;ctx.beginPath();vals.forEach((v,i)=>{const x=xf(i),y=h-25-(v-1)*(h-50)/4;i?ctx.lineTo(x,y):ctx.moveTo(x,y);ctx.fillStyle='#1769e0';ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fill();ctx.beginPath();i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#697589';ctx.font='9px Inter';labels.forEach((l,i)=>ctx.fillText(l,xf(i)-18,h-7))}
function renderRanking(){const body=$('#rankingBody');if(!body)return;const p=$('#rankingPeriod')?.value||'all',q=($('#rankingSearch')?.value||'').toLowerCase();const ev=db.evaluations.filter(e=>(p==='all'||e.period===p)&&(`${e.coordinator} ${e.unit}`).toLowerCase().includes(q)).sort((a,b)=>b.final-a.final);body.innerHTML=ev.length?ev.map((e,i)=>`<tr><td><b>${i+1}</b></td><td><b>${esc(e.coordinator)}</b><br><small>${esc(e.period)}</small></td><td>${esc(e.unit)}</td><td><span class="score-pill">${Number(e.final).toFixed(2)}</span></td><td><span class="badge ${classification(e.final)[1]}">${esc(e.classification)}</span></td><td>${Number(e.pillars?.kpis||0).toFixed(2)}</td><td>${Number(e.pillars?.lead||0).toFixed(2)}</td><td>${Number(e.pillars?.quality||0).toFixed(2)}</td><td>${Number(e.pillars?.innovation||0).toFixed(2)}</td><td>${Number(e.pillars?.client||0).toFixed(2)}</td></tr>`).join(''):'<tr><td colspan="10">Nenhum resultado encontrado.</td></tr>'}
function renderPdi(){const body=$('#pdiBody');if(!body)return;body.innerHTML=db.pdi.length?db.pdi.map(x=>`<tr><td><b>${esc(x.gap)}</b></td><td>${esc(x.goal)}</td><td>${esc(x.action)}</td><td>${esc(x.owner)}</td><td>${esc(x.deadline)}</td><td>${esc(x.indicator)}</td><td><select data-pdi="${esc(x.id)}"><option ${x.status==='Planejado'?'selected':''}>Planejado</option><option ${x.status==='Em andamento'?'selected':''}>Em andamento</option><option ${x.status==='Concluído'?'selected':''}>Concluído</option><option ${x.status==='Atrasado'?'selected':''}>Atrasado</option></select></td></tr>`).join(''):'<tr><td colspan="7">Nenhuma ação de PDI cadastrada.</td></tr>';body.querySelectorAll('select[data-pdi]').forEach(s=>s.addEventListener('change',()=>updatePdi(s.dataset.pdi,s.value)))}
function updatePdi(id,status){const x=db.pdi.find(p=>p.id===id);if(x){x.status=status;save()}}
function renderCoords(){const body=$('#coordBody');if(!body)return;body.innerHTML=db.coordinators.length?db.coordinators.map(c=>{const es=db.evaluations.filter(e=>e.coordinatorId===c.id).sort((a,b)=>(b.period||'').localeCompare(a.period||'')),last=es[0];return`<tr><td><b>${esc(c.name)}</b></td><td>${esc(c.unit)}</td><td>${esc(c.region||'—')}</td><td><span class="badge green">Ativo</span></td><td>${es.length}</td><td>${last?Number(last.final).toFixed(2):'—'}</td></tr>`}).join(''):'<tr><td colspan="6">Nenhum coordenador cadastrado. Use “+ Novo coordenador”.</td></tr>'}
function renderWeights(){const w=$('#weights');if(w)w.innerHTML=pillars.map(p=>`<div class="weight"><span>${p.name}</span><b>${p.weight*100}%</b></div>`).join('')}
function renderAll(){renderCoordinatorSelect();renderFilters();renderDashboard();renderRanking();renderPdi();renderCoords();renderWeights()}
function openModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}
function newCoordinator(){openModal(`<h2>Novo coordenador</h2><form class="modal-form" id="coordForm"><label>Nome<input name="name" required placeholder="Nome completo"></label><label>Unidade<input name="unit" required placeholder="Ex.: Horizontina"></label><label>Região<input name="region" placeholder="Ex.: Sul"></label><div class="modal-actions"><button type="button" class="ghost" id="cancelModal">Cancelar</button><button class="primary">Cadastrar</button></div></form>`);$('#cancelModal').onclick=closeModal;$('#coordForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);db.coordinators.push({id:uid(),name:f.get('name'),unit:f.get('unit'),region:f.get('region')});closeModal();save();go('coordenadores')}}
function newPdi(){openModal(`<h2>Nova ação de PDI</h2><form class="modal-form" id="pdiForm"><label>Competência / Gap<input name="gap" required></label><label>Objetivo<input name="goal" required></label><label>Ação de desenvolvimento<input name="action" required></label><label>Responsável<input name="owner" required></label><label>Prazo<input name="deadline" type="date" required></label><label>Indicador de sucesso<input name="indicator" required></label><div class="modal-actions"><button type="button" class="ghost" id="cancelModal">Cancelar</button><button class="primary">Adicionar ação</button></div></form>`);$('#cancelModal').onclick=closeModal;$('#pdiForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);db.pdi.push({id:uid(),gap:f.get('gap'),goal:f.get('goal'),action:f.get('action'),owner:f.get('owner'),deadline:f.get('deadline'),indicator:f.get('indicator'),status:'Planejado'});closeModal();save();go('pdi')}}
function submitEvaluation(e){e.preventDefault();const f=new FormData(e.target),c=db.coordinators.find(x=>x.id===f.get('coordinator'));if(!c){alert('Selecione um coordenador.');return}const ps=pillars.map((p,pi)=>{const nums=p.items.map((_,ii)=>Number(f.get(`score_${pi}_${ii}`)));return nums.reduce((a,b)=>a+b,0)/nums.length});const final=ps.reduce((sum,n,i)=>sum+n*pillars[i].weight,0),cl=classification(final)[0];db.evaluations.push({id:uid(),coordinatorId:c.id,coordinator:c.name,unit:f.get('unit'),period:f.get('period'),eval1:f.get('eval1'),eval2:f.get('eval2'),final,classification:cl,pillars:{kpis:ps[0],lead:ps[1],quality:ps[2],innovation:ps[3],client:ps[4]},createdAt:new Date().toISOString()});save();e.target.reset();alert('Avaliação salva com sucesso.');go('dashboard')}
function exportData(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='performance-security-dados.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function init(){initNav();renderCriteria();renderAll();go('dashboard')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
