(function(){'use strict';
var KEY='securityPerformanceJD_v4';
var db={coordinators:[],evaluations:[],pdi:[]};
var pillars=[
{name:'Gestão dos KPIs Operacionais',weight:.30,items:['Turnover','Absenteísmo','Horas extras','Postos descobertos']},
{name:'Desenvolvimento da Liderança',weight:.20,items:['Postura','Gestão de equipe','Treinamentos','Comunicação','Formação de novos líderes']},
{name:'Qualidade Operacional e Segurança',weight:.20,items:['Procedimentos John Deere','Auditorias e não conformidades','Gestão de ocorrências','Inspeções e vulnerabilidades']},
{name:'Inovação e Melhoria Contínua',weight:.15,items:['Iniciativas de inovação','Resultados das iniciativas']},
{name:'Gestão do Cliente e Compliance',weight:.15,items:['Processos OEA','Relacionamento com cliente','Compliance e governança']}];
var $=function(s){return document.querySelector(s)},$$=function(s){return Array.from(document.querySelectorAll(s))};
function uid(){return 'id_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8)}
function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]})}
function load(){try{var x=JSON.parse(localStorage.getItem(KEY)||'null');if(x&&typeof x==='object'){db=x}}catch(e){};['coordinators','evaluations','pdi'].forEach(function(k){if(!Array.isArray(db[k]))db[k]=[]})}
function save(){localStorage.setItem(KEY,JSON.stringify(db));renderAll()}
function classification(n){n=Number(n)||0;return n>=4.5?'Excepcional':n>=4?'Acima do esperado':n>=3?'Dentro do esperado':n>=2?'Necessita desenvolvimento':'Performance crítica'}
function go(view){var el=$('#view-'+view);if(!el)return;$$('.view').forEach(function(x){x.classList.remove('active-view')});el.classList.add('active-view');$$('.nav-item').forEach(function(x){x.classList.toggle('active',x.dataset.view===view)});var t={dashboard:'Dashboard Executivo',avaliacao:'Avaliação 180°',ranking:'Ranking',pdi:'Plano de Desenvolvimento Individual',coordenadores:'Coordenadores',config:'Configurações'};if($('#pageTitle'))$('#pageTitle').textContent=t[view]||'Gestão de Performance';if(view==='avaliacao')renderCriteria();window.scrollTo(0,0)}
function renderCriteria(){var box=$('#criteriaContainer');if(!box)return;var h='<div class="eval-help"><b>Como avaliar:</b> escolha uma nota de 1 a 5 em cada critério. A nota 3 significa "Dentro do esperado". <button type="button" class="ghost" id="fillThree">Preencher tudo com 3</button> '+(db.coordinators.length?'':'<button type="button" class="ghost" id="quickCoordinator">+ Cadastrar coordenador</button>')+'</div>';pillars.forEach(function(p,pi){h+='<div class="criteria-group"><div class="criteria-title"><strong>'+p.name+'</strong><span>Peso '+p.weight*100+'%</span></div>';p.items.forEach(function(n,ii){h+='<div class="criterion"><div class="criterion-name"><b>'+n+'</b><span>Evidência / observação</span></div><div><input class="score-input" min="1" max="5" step="0.1" type="number" name="score_'+pi+'_'+ii+'" placeholder="Nota"><div class="score-buttons">'+[1,2,3,4,5].map(function(v){return '<button type="button" class="score-btn" data-score="'+pi+'_'+ii+'" data-value="'+v+'">'+v+'</button>'}).join('')+'</div></div><textarea name="obs_'+pi+'_'+ii+'" placeholder="Evidência / observação"></textarea></div>')});h+='</div>'});box.innerHTML=h}
function renderSelect(selected){var s=$('#evalCoordinator');if(!s)return;var old=selected||s.value||'';s.innerHTML='<option value="">Selecione o coordenador...</option>'+db.coordinators.map(function(c){return '<option value="'+esc(c.id)+'">'+esc(c.name)+' — '+esc(c.unit)+'</option>'}).join('');s.value=old}
function renderCoords(){var b=$('#coordBody');if(!b)return;b.innerHTML=db.coordinators.length?db.coordinators.map(function(c){var es=db.evaluations.filter(function(e){return e.coordinatorId===c.id});var last=es[es.length-1];return '<tr><td><b>'+esc(c.name)+'</b></td><td>'+esc(c.unit)+'</td><td>'+esc(c.region||'—')+'</td><td><span class="badge green">Ativo</span></td><td>'+es.length+'</td><td>'+(last?Number(last.final).toFixed(2):'—')+'</td></tr>'}).join(''):'<tr><td colspan="6">Nenhum coordenador cadastrado.</td></tr>'}
function renderPdi(){var b=$('#pdiBody');if(!b)return;b.innerHTML=db.pdi.length?db.pdi.map(function(x){return '<tr><td>'+esc(x.gap)+'</td><td>'+esc(x.goal)+'</td><td>'+esc(x.action)+'</td><td>'+esc(x.owner)+'</td><td>'+esc(x.deadline)+'</td><td>'+esc(x.indicator)+'</td><td><select data-pdi="'+esc(x.id)+'"><option '+(x.status==='Planejado'?'selected':'')+'>Planejado</option><option '+(x.status==='Em andamento'?'selected':'')+'>Em andamento</option><option '+(x.status==='Concluído'?'selected':'')+'>Concluído</option><option '+(x.status==='Atrasado'?'selected':'')+'>Atrasado</option></select></td></tr>'}).join(''):'<tr><td colspan="7">Nenhuma ação de PDI cadastrada.</td></tr>'}
function renderRanking(){var b=$('#rankingBody');if(!b)return;var q=($('#rankingSearch')||{}).value||'',p=($('#rankingPeriod')||{}).value||'all';var es=db.evaluations.filter(function(e){return(p==='all'||e.period===p)&&String(e.coordinator+' '+e.unit).toLowerCase().includes(q.toLowerCase())}).sort(function(a,b){return b.final-a.final});b.innerHTML=es.length?es.map(function(e,i){return '<tr><td>'+String(i+1)+'</td><td><b>'+esc(e.coordinator)+'</b></td><td>'+esc(e.unit)+'</td><td><b>'+Number(e.final).toFixed(2)+'</b></td><td>'+esc(e.classification)+'</td><td>'+Number(e.pillars.kpis).toFixed(2)+'</td><td>'+Number(e.pillars.lead).toFixed(2)+'</td><td>'+Number(e.pillars.quality).toFixed(2)+'</td><td>'+Number(e.pillars.innovation).toFixed(2)+'</td><td>'+Number(e.pillars.client).toFixed(2)+'</td></tr>'}).join(''):'<tr><td colspan="10">Nenhum resultado encontrado.</td></tr>'}
function renderDashboard(){var es=db.evaluations,avg=es.length?es.reduce(function(a,e){return a+Number(e.final)},0)/es.length:0;function set(id,v){var e=$('#'+id);if(e)e.textContent=v}set('kpiCoordinators',db.coordinators.length);set('kpiEvaluations',es.length);set('kpiAverage',es.length?avg.toFixed(2):'—');var done=db.pdi.filter(function(x){return x.status==='Concluído'}).length;set('kpiPdi',db.pdi.length?Math.round(done/db.pdi.length*100)+'%':'0%');var top=es.slice().sort(function(a,b){return b.final-a.final}).slice(0,5);if($('#topRanking'))$('#topRanking').innerHTML=top.length?top.map(function(e,i){return '<div class="rank-row"><span class="rank-num">'+(i+1)+'</span><div class="rank-name"><b>'+esc(e.coordinator)+'</b><span>'+esc(e.unit)+' • '+esc(e.period)+'</span></div><span class="score">'+Number(e.final).toFixed(2)+'</span></div>'}).join(''):'<div class="empty-chart">Nenhuma avaliação cadastrada.</div>'}
function renderFilters(){var ps=[...new Set(db.evaluations.map(function(e){return e.period}).filter(Boolean))].sort().reverse();['dashPeriod','rankingPeriod'].forEach(function(id){var s=$('#'+id);if(s){var old=s.value;s.innerHTML='<option value="all">Todos os períodos</option>'+ps.map(function(p){return '<option value="'+esc(p)+'">'+esc(p)+'</option>'}).join('');s.value=ps.includes(old)?old:'all'}});var us=[...new Set(db.evaluations.map(function(e){return e.unit}).filter(Boolean))].sort(),u=$('#dashUnit');if(u){var old=u.value;u.innerHTML='<option value="all">Todas as unidades</option>'+us.map(function(x){return '<option>'+esc(x)+'</option>'}).join('');u.value=us.includes(old)?old:'all'}}
function renderWeights(){var b=$('#weights');if(b)b.innerHTML=pillars.map(function(p){return '<div class="weight"><span>'+p.name+'</span><b>'+p.weight*100+'%</b></div>'}).join('')}
function renderHistory(){var f=$('#evaluationForm');if(!f)return;var old=$('#evaluationHistory');if(old)old.remove();var s=document.createElement('section');s.id='evaluationHistory';s.className='panel';s.style.marginTop='16px';var es=db.evaluations.slice().reverse();s.innerHTML='<div class="panel-head"><div><h2>Avaliações registradas</h2><p>Edite ou exclua avaliações salvas.</p></div></div>'+(es.length?'<div class="table-scroll"><table><thead><tr><th>Coordenador</th><th>Período</th><th>Nota</th><th>Ações</th></tr></thead><tbody>'+es.map(function(e){return '<tr><td>'+esc(e.coordinator)+'</td><td>'+esc(e.period)+'</td><td><b>'+Number(e.final).toFixed(2)+'</b></td><td><button type="button" class="ghost" data-edit-eval="'+e.id+'">Editar</button> <button type="button" class="ghost" data-delete-eval="'+e.id+'">Excluir</button></td></tr>'}).join('')+'</tbody></table></div>':'<div class="empty-chart">Nenhuma avaliação cadastrada.</div>');f.insertAdjacentElement('afterend',s)}
function renderAll(){renderSelect();renderCoords();renderPdi();renderRanking();renderFilters();renderDashboard();renderWeights();renderHistory()}
function modal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden')}
function closeModal(){if($('#modal'))$('#modal').classList.add('hidden')}
function newCoordinator(){modal('<h2>Novo coordenador</h2><form id="coordForm" class="modal-form"><label>Nome<input name="name" required></label><label>Unidade<input name="unit" required></label><label>Região<input name="region"></label><div class="modal-actions"><button type="button" class="ghost" data-close-modal>Cancelar</button><button class="primary">Cadastrar</button></div></form>')}
function newPdi(){modal('<h2>Nova ação de PDI</h2><form id="pdiForm" class="modal-form"><label>Competência / Gap<input name="gap" required></label><label>Objetivo<input name="goal" required></label><label>Ação<input name="action" required></label><label>Responsável<input name="owner" required></label><label>Prazo<input name="deadline" type="date" required></label><label>Indicador<input name="indicator" required></label><div class="modal-actions"><button type="button" class="ghost" data-close-modal>Cancelar</button><button class="primary">Adicionar ação</button></div></form>')}
function editEval(e){go('avaliacao');setTimeout(function(){renderCriteria();renderSelect(e.coordinatorId);$('#evalUnit').value=e.unit||'';$('#evalPeriod').value=e.period||'';$('#eval1').value=e.eval1||'';$('#eval2').value=e.eval2||'';pillars.forEach(function(p,pi){p.items.forEach(function(n,ii){var a=$('[name="score_'+pi+'_'+ii+'"]'),o=$('[name="obs_'+pi+'_'+ii+'"]');if(a)a.value=e.scores[pi][ii];if(o)o.value=e.observations[pi][ii]})});$('#evaluationForm').dataset.editId=e.id;$('#evaluationForm button[type="submit"]').textContent='Atualizar avaliação'},0)}
function saveEvaluation(form){var fd=new FormData(form),c=db.coordinators.find(function(x){return x.id===fd.get('coordinator')});var missing=[];pillars.forEach(function(p,pi){p.items.forEach(function(n,ii){var v=Number(fd.get('score_'+pi+'_'+ii));if(!(v>=1&&v<=5))missing.push(n)})});if(!c){alert('Selecione ou cadastre um coordenador.');return}if(!fd.get('evalUnit')||!fd.get('evalPeriod')||!fd.get('eval1')||!fd.get('eval2')){alert('Preencha coordenador, unidade, período e os dois avaliadores.');return}if(missing.length){alert('Faltam '+missing.length+' notas. Clique em uma nota de 1 a 5 ou use “Preencher tudo com 3”.');return}var scores=[],obs=[],av=[];pillars.forEach(function(p,pi){var a=[],o=[];p.items.forEach(function(n,ii){a.push(Number(fd.get('score_'+pi+'_'+ii)));o.push(fd.get('obs_'+pi+'_'+ii)||'')});scores.push(a);obs.push(o);av.push(a.reduce(function(x,y){return x+y},0)/a.length)});var final=av.reduce(function(s,n,i){return s+n*pillars[i].weight},0),id=form.dataset.editId||uid(),item={id:id,coordinatorId:c.id,coordinator:c.name,unit:fd.get('evalUnit'),period:fd.get('evalPeriod'),eval1:fd.get('eval1'),eval2:fd.get('eval2'),final:final,classification:classification(final),pillars:{kpis:av[0],lead:av[1],quality:av[2],innovation:av[3],client:av[4]},scores:scores,observations:obs,createdAt:new Date().toISOString()},idx=db.evaluations.findIndex(function(x){return x.id===id});if(idx>=0)db.evaluations[idx]=item;else db.evaluations.push(item);delete form.dataset.editId;save();form.reset();renderCriteria();alert(idx>=0?'Avaliação atualizada com sucesso!':'Avaliação salva com sucesso!');go('dashboard')}
function init(){load();$$('[data-view]').forEach(function(b){b.addEventListener('click',function(e){e.preventDefault();go(b.dataset.view)})});$$('[data-go]').forEach(function(b){b.addEventListener('click',function(e){e.preventDefault();go(b.dataset.go)})});if($('#menuBtn'))$('#menuBtn').addEventListener('click',function(){$('#sidebar').classList.toggle('open')});if($('#addCoordinatorBtn'))$('#addCoordinatorBtn').addEventListener('click',newCoordinator);if($('#addPdiBtn'))$('#addPdiBtn').addEventListener('click',newPdi);if($('#modalClose'))$('#modalClose').addEventListener('click',closeModal);document.addEventListener('click',function(e){var b=e.target.closest('.score-btn');if(b){var x=$('[name="score_'+b.dataset.score+'"]');if(x)x.value=b.dataset.value;$$('[data-score="'+b.dataset.score+'"]').forEach(function(q){q.classList.toggle('selected',q===b)})}if(e.target.id==='quickCoordinator')newCoordinator();if(e.target.id==='fillThree')$$('.score-input').forEach(function(x){x.value=3});if(e.target.closest('[data-close-modal]'))closeModal();var ed=e.target.closest('[data-edit-eval]');if(ed){var ev=db.evaluations.find(function(x){return x.id===ed.dataset.editEval});if(ev)editEval(ev)}var de=e.target.closest('[data-delete-eval]');if(de&&confirm('Excluir esta avaliação?')){db.evaluations=db.evaluations.filter(function(x){return x.id!==de.dataset.deleteEval});save()}});document.addEventListener('submit',function(e){if(e.target.id==='evaluationForm'){e.preventDefault();saveEvaluation(e.target)}if(e.target.id==='coordForm'){e.preventDefault();var f=new FormData(e.target);db.coordinators.push({id:uid(),name:f.get('name'),unit:f.get('unit'),region:f.get('region')});closeModal();save();go('coordenadores')}if(e.target.id==='pdiForm'){e.preventDefault();var f=new FormData(e.target);db.pdi.push({id:uid(),gap:f.get('gap'),goal:f.get('goal'),action:f.get('action'),owner:f.get('owner'),deadline:f.get('deadline'),indicator:f.get('indicator'),status:'Planejado'});closeModal();save();go('pdi')}});document.addEventListener('change',function(e){if(e.target.id==='evalCoordinator'){var c=db.coordinators.find(function(x){return x.id===e.target.value});if(c)$('#evalUnit').value=c.unit}if(e.target.dataset.pdi){var p=db.pdi.find(function(x){return x.id===e.target.dataset.pdi});if(p){p.status=e.target.value;save()}}if(e.target.id==='rankingPeriod')renderRanking();if(e.target.id==='dashPeriod'||e.target.id==='dashUnit')renderDashboard()});document.addEventListener('input',function(e){if(e.target.id==='rankingSearch')renderRanking()});renderCriteria();renderAll();go('dashboard')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();})();