(function(){'use strict';
var KEY='securityPerformanceJD_v3',db={coordinators:[],evaluations:[],pdi:[]};
var pillars=[
{name:'Gestão dos KPIs Operacionais',weight:.30,items:['Turnover','Absenteísmo','Horas extras','Postos descobertos']},
{name:'Desenvolvimento da Liderança',weight:.20,items:['Postura','Gestão de equipe','Treinamentos','Comunicação','Formação de novos líderes']},
{name:'Qualidade Operacional e Segurança',weight:.20,items:['Procedimentos John Deere','Auditorias e não conformidades','Gestão de ocorrências','Inspeções e vulnerabilidades']},
{name:'Inovação e Melhoria Contínua',weight:.15,items:['Iniciativas de inovação','Resultados das iniciativas']},
{name:'Gestão do Cliente e Compliance',weight:.15,items:['Processos OEA','Relacionamento com cliente','Compliance e governança']}];
function $(s){return document.querySelector(s)} function all(s){return Array.prototype.slice.call(document.querySelectorAll(s))}
function uid(){return 'id_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8)}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]})}
function load(){try{var x=JSON.parse(localStorage.getItem(KEY));if(x&&typeof x==='object')db=x}catch(e){};if(!Array.isArray(db.coordinators))db.coordinators=[];if(!Array.isArray(db.evaluations))db.evaluations=[];if(!Array.isArray(db.pdi))db.pdi=[]}
function save(){localStorage.setItem(KEY,JSON.stringify(db));renderAll()}
function cls(n){n=Number(n)||0;return n>=4.5?['Excepcional','green']:n>=4?['Acima do esperado','green']:n>=3?['Dentro do esperado','yellow']:n>=2?['Necessita desenvolvimento','red']:['Performance crítica','red']}
function go(v){var t=$('#view-'+v);if(!t)return;all('.view').forEach(function(x){x.classList.remove('active-view')});t.classList.add('active-view');all('.nav-item').forEach(function(x){x.classList.toggle('active',x.getAttribute('data-view')===v)});var titles={dashboard:'Dashboard Executivo',avaliacao:'Avaliação 180°',ranking:'Ranking',pdi:'Plano de Desenvolvimento Individual',coordenadores:'Coordenadores',config:'Configurações'};if($('#pageTitle'))$('#pageTitle').textContent=titles[v]||'Gestão de Performance';if(v==='avaliacao')renderCriteria();window.scrollTo(0,0)}
function renderCriteria(){var box=$('#criteriaContainer');if(!box)return;var h='<div class="eval-help">Avalie cada critério de <b>1 a 5</b>. Clique na nota ou digite o valor. '+(db.coordinators.length?'':'<button type="button" class="ghost" id="quickCoordinator">+ Cadastrar coordenador</button>')+'</div>';pillars.forEach(function(p,pi){h+='<div class="criteria-group"><div class="criteria-title"><strong>'+p.name+'</strong><span>Peso '+p.weight*100+'% • notas 1 a 5</span></div>';p.items.forEach(function(name,ii){h+='<div class="criterion"><div class="criterion-name"><b>'+name+'</b><span>Registre evidência ou observação.</span></div><div><input class="score-input" required min="1" max="5" step="0.1" type="number" name="score_'+pi+'_'+ii+'" placeholder="Nota"><div class="score-buttons">'+[1,2,3,4,5].map(function(n){return '<button type="button" class="score-btn" data-score="'+pi+'_'+ii+'" data-value="'+n+'">'+n+'</button>'}).join('')+'</div></div><textarea name="obs_'+pi+'_'+ii+'" placeholder="Evidência / observação"></textarea></div>')});h+='</div>'});box.innerHTML=h}
function renderSelect(selected){var s=$('#evalCoordinator');if(!s)return;var old=selected||s.value||'';s.innerHTML='<option value="">Selecione o coordenador...</option>'+db.coordinators.map(function(c){return '<option value="'+esc(c.id)+'">'+esc(c.name)+' — '+esc(c.unit)+'</option>'}).join('');s.value=old}
function renderFilters(){var ps=[],us=[];db.evaluations.forEach(function(e){if(e.period&&ps.indexOf(e.period)<0)ps.push(e.period);if(e.unit&&us.indexOf(e.unit)<0)us.push(e.unit)});ps.sort().reverse();us.sort();['dashPeriod','rankingPeriod'].forEach(function(id){var x=$('#'+id);if(x){var o=x.value;x.innerHTML='<option value="all">Todos os períodos</option>'+ps.map(function(p){return '<option>'+esc(p)+'</option>'}).join('');x.value=ps.indexOf(o)>=0?o:'all'}});var d=$('#dashUnit');if(d){var od=d.value;d.innerHTML='<option value="all">Todas as unidades</option>'+us.map(function(u){return '<option>'+esc(u)+'</option>'}).join('');d.value=us.indexOf(od)>=0?od:'all'}}
function filtered(){var p=$('#dashPeriod')?$('#dashPeriod').value:'all',u=$('#dashUnit')?$('#dashUnit').value:'all';return db.evaluations.filter(function(e){return(p==='all'||e.period===p)&&(u==='all'||e.unit===u)})}
function renderDashboard(){var ev=filtered(),avg=ev.length?ev.reduce(function(a,e){return a+Number(e.final)},0)/ev.length:null;function set(id,v){if($('#'+id))$('#'+id).textContent=v}set('kpiCoordinators',db.coordinators.length);set('kpiEvaluations',ev.length);set('kpiAverage',avg==null?'—':avg.toFixed(2));set('kpiPdi',db.pdi.length?Math.round(db.pdi.filter(function(x){return x.status==='Concluído'}).length/db.pdi.length*100)+'%':'0%');var c={'Excepcional':0,'Acima do esperado':0,'Dentro do esperado':0,'Necessita desenvolvimento':0,'Performance crítica':0};ev.forEach(function(e){if(c[e.classification]!=null)c[e.classification]++});var mx=Math.max(1,c['Excepcional'],c['Acima do esperado'],c['Dentro do esperado'],c['Necessita desenvolvimento'],c['Performance crítica']);if($('#distribution'))$('#distribution').innerHTML=Object.keys(c).map(function(k){return '<div class="dist-row"><span>'+k+'</span><div class="bar"><i style="width:'+c[k]/mx*100+'%"></i></div><b>'+c[k]+'</b></div>'}).join('');var r=ev.slice().sort(function(a,b){return b.final-a.final}).slice(0,5);if($('#topRanking'))$('#topRanking').innerHTML=r.length?r.map(function(e,i){return '<div class="rank-row"><span class="rank-num">'+(i+1)+'</span><div class="rank-name"><b>'+esc(e.coordinator)+'</b><span>'+esc(e.unit)+' • '+esc(e.period)+'</span></div><span class="score">'+Number(e.final).toFixed(2)+'</span></div>'}).join(''):'<div class="empty-chart">Nenhuma avaliação cadastrada.</div>';if($('#attention'))$('#attention').innerHTML=ev.slice().sort(function(a,b){return a.final-b.final}).slice(0,4).map(function(e){var q=cls(e.final);return '<div class="attention-row"><span>'+esc(e.coordinator)+'<br><small>'+esc(e.unit)+'</small></span><span class="badge '+q[1]+'">'+Number(e.final).toFixed(2)+' • '+q[0]+'</span></div>'}).join('')||'<div class="empty-chart">Sem pontos de atenção.</div>'}
function renderRanking(){var b=$('#rankingBody');if(!b)return;var p=$('#rankingPeriod')?$('#rankingPeriod').value:'all',q=$('#rankingSearch')?$('#rankingSearch').value.toLowerCase():'';var e=db.evaluations.filter(function(x){return(p==='all'||x.period===p)&&(String(x.coordinator+' '+x.unit).toLowerCase().indexOf(q)>=0)}).sort(function(a,b){return b.final-a.final});b.innerHTML=e.length?e.map(function(x,i){return '<tr><td>'+String(i+1)+'</td><td><b>'+esc(x.coordinator)+'</b></td><td>'+esc(x.unit)+'</td><td><b>'+Number(x.final).toFixed(2)+'</b></td><td><span class="badge '+cls(x.final)[1]+'">'+esc(x.classification)+'</span></td><td>'+Number(x.pillars.kpis).toFixed(2)+'</td><td>'+Number(x.pillars.lead).toFixed(2)+'</td><td>'+Number(x.pillars.quality).toFixed(2)+'</td><td>'+Number(x.pillars.innovation).toFixed(2)+'</td><td>'+Number(x.pillars.client).toFixed(2)+'</td></tr>'}).join(''):'<tr><td colspan="10">Nenhum resultado encontrado.</td></tr>'}
function renderPdi(){var b=$('#pdiBody');if(!b)return;b.innerHTML=db.pdi.length?db.pdi.map(function(x){return '<tr><td>'+esc(x.gap)+'</td><td>'+esc(x.goal)+'</td><td>'+esc(x.action)+'</td><td>'+esc(x.owner)+'</td><td>'+esc(x.deadline)+'</td><td>'+esc(x.indicator)+'</td><td><select data-pdi="'+esc(x.id)+'"><option '+(x.status==='Planejado'?'selected':'')+'>Planejado</option><option '+(x.status==='Em andamento'?'selected':'')+'>Em andamento</option><option '+(x.status==='Concluído'?'selected':'')+'>Concluído</option><option '+(x.status==='Atrasado'?'selected':'')+'>Atrasado</option></select></td></tr>'}).join(''):'<tr><td colspan="7">Nenhuma ação de PDI cadastrada.</td></tr>'}
function renderCoords(){var b=$('#coordBody');if(!b)return;b.innerHTML=db.coordinators.length?db.coordinators.map(function(c){var e=db.evaluations.filter(function(x){return x.coordinatorId===c.id});var last=e[e.length-1];return '<tr><td><b>'+esc(c.name)+'</b></td><td>'+esc(c.unit)+'</td><td>'+esc(c.region||'—')+'</td><td><span class="badge green">Ativo</span></td><td>'+e.length+'</td><td>'+(last?Number(last.final).toFixed(2):'—')+'</td></tr>'}).join(''):'<tr><td colspan="6">Nenhum coordenador cadastrado.</td></tr>'}
function renderWeights(){if($('#weights'))$('#weights').innerHTML=pillars.map(function(p){return '<div class="weight"><span>'+p.name+'</span><b>'+p.weight*100+'%</b></div>'}).join('')}
function renderHistory(){var f=$('#evaluationForm');if(!f)return;var old=$('#evaluationHistory');if(old)old.remove();var s=document.createElement('section');s.id='evaluationHistory';s.className='panel';s.style.marginTop='16px';var rows=db.evaluations.slice().reverse();s.innerHTML='<div class="panel-head"><div><h2>Avaliações registradas</h2><p>Use Editar para alterar uma avaliação.</p></div></div>'+(rows.length?'<div class="table-scroll"><table><thead><tr><th>Coordenador</th><th>Período</th><th>Nota</th><th>Ações</th></tr></thead><tbody>'+rows.map(function(e){return '<tr><td>'+esc(e.coordinator)+'</td><td>'+esc(e.period)+'</td><td><b>'+Number(e.final).toFixed(2)+'</b></td><td><button type="button" class="ghost" data-edit-eval="'+esc(e.id)+'">Editar</button> <button type="button" class="ghost" data-delete-eval="'+esc(e.id)+'">Excluir</button></td></tr>'}).join('')+'</tbody></table></div>':'<div class="empty-chart">Nenhuma avaliação cadastrada.</div>');f.insertAdjacentElement('afterend',s)}
function renderAll(){renderSelect();renderFilters();renderDashboard();renderRanking();renderPdi();renderCoords();renderWeights();renderHistory()}
function openModal(h){$('#modalContent').innerHTML=h;$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}
function newCoordinator(){openModal('<h2>Novo coordenador</h2><form id="coordForm" class="modal-form"><label>Nome<input name="name" required></label><label>Unidade<input name="unit" required></label><label>Região<input name="region"></label><div class="modal-actions"><button type="button" class="ghost" data-close-modal>Cancelar</button><button type="submit" class="primary">Cadastrar</button></div></form>')}
function newPdi(){openModal('<h2>Nova ação de PDI</h2><form id="pdiForm" class="modal-form"><label>Competência / Gap<input name="gap" required></label><label>Objetivo<input name="goal" required></label><label>Ação<input name="action" required></label><label>Responsável<input name="owner" required></label><label>Prazo<input name="deadline" type="date" required></label><label>Indicador<input name="indicator" required></label><div class="modal-actions"><button type="button" class="ghost" data-close-modal>Cancelar</button><button type="submit" class="primary">Adicionar ação</button></div></form>')}
function editEval(e){go('avaliacao');setTimeout(function(){renderCriteria();renderSelect(e.coordinatorId);$('#evalUnit').value=e.unit||'';$('#evalPeriod').value=e.period||'';$('#eval1').value=e.eval1||'';$('#eval2').value=e.eval2||'';pillars.forEach(function(p,pi){p.items.forEach(function(n,ii){var a=$('[name="score_'+pi+'_'+ii+'"]');var o=$('[name="obs_'+pi+'_'+ii+'"]');if(a)a.value=e.scores&&e.scores[pi]?e.scores[pi][ii]:'';if(o)o.value=e.observations&&e.observations[pi]?e.observations[pi][ii]:''})});$('#evaluationForm').dataset.editId=e.id;$('#evaluationForm button[type="submit"]').textContent='Atualizar avaliação'},30)}
function submit(form){var fd=new FormData(form),c=db.coordinators.filter(function(x){return x.id===fd.get('coordinator')})[0];if(!c){alert('Cadastre ou selecione um coordenador antes de salvar.');return false}var scores=[],obs=[],av=[];pillars.forEach(function(p,pi){var a=[],o=[];p.items.forEach(function(n,ii){var v=Number(fd.get('score_'+pi+'_'+ii));if(!v||v<1||v>5)throw new Error('Informe todas as notas de 1 a 5.');a.push(v);o.push(fd.get('obs_'+pi+'_'+ii)||'')});scores.push(a);obs.push(o);av.push(a.reduce(function(x,y){return x+y},0)/a.length)});var final=av.reduce(function(s,n,i){return s+n*pillars[i].weight},0),id=form.dataset.editId||uid(),item={id:id,coordinatorId:c.id,coordinator:c.name,unit:fd.get('evalUnit'),period:fd.get('evalPeriod'),eval1:fd.get('eval1'),eval2:fd.get('eval2'),final:final,classification:cls(final)[0],pillars:{kpis:av[0],lead:av[1],quality:av[2],innovation:av[3],client:av[4]},scores:scores,observations:obs,createdAt:new Date().toISOString()},idx=db.evaluations.findIndex(function(x){return x.id===id});if(idx>=0)db.evaluations[idx]=item;else db.evaluations.push(item);delete form.dataset.editId;save();form.reset();renderCriteria();alert(idx>=0?'Avaliação atualizada com sucesso!':'Avaliação salva com sucesso!');go('dashboard');return true}
function init(){load();document.addEventListener('click',function(e){var v=e.target.closest('[data-view]');if(v){e.preventDefault();go(v.getAttribute('data-view'));return}var g=e.target.closest('[data-go]');if(g){e.preventDefault();go(g.getAttribute('data-go'));return}var sb=e.target.closest('[data-score]');if(sb){var x=$('[name="score_'+sb.getAttribute('data-score')+'"]');if(x)x.value=sb.getAttribute('data-value');all('[data-score="'+sb.getAttribute('data-score')+'"]').forEach(function(b){b.classList.toggle('selected',b===sb)});return}if(e.target.closest('#quickCoordinator')){newCoordinator();return}if(e.target.closest('#addCoordinatorBtn')){newCoordinator();return}if(e.target.closest('#addPdiBtn')){newPdi();return}if(e.target.closest('#modalClose')||e.target.closest('[data-close-modal]')){closeModal();return}var ed=e.target.closest('[data-edit-eval]');if(ed){var ev=db.evaluations.find(function(x){return x.id===ed.getAttribute('data-edit-eval')});if(ev)editEval(ev);return}var de=e.target.closest('[data-delete-eval]');if(de&&confirm('Excluir esta avaliação?')){db.evaluations=db.evaluations.filter(function(x){return x.id!==de.getAttribute('data-delete-eval')});save();return}if(e.target.closest('#clearFilters')){$('#dashPeriod').value='all';$('#dashUnit').value='all';renderDashboard();return}if(e.target.closest('#menuBtn')){$('#sidebar').classList.toggle('open');return}if(e.target.closest('#exportBtn')){exportData();return}});document.addEventListener('submit',function(e){if(e.target.id==='evaluationForm'){e.preventDefault();try{submit(e.target)}catch(err){alert(err.message)}}if(e.target.id==='coordForm'){e.preventDefault();var f=new FormData(e.target);db.coordinators.push({id:uid(),name:f.get('name'),unit:f.get('unit'),region:f.get('region')});closeModal();save();go('coordenadores')}if(e.target.id==='pdiForm'){e.preventDefault();var p=new FormData(e.target);db.pdi.push({id:uid(),gap:p.get('gap'),goal:p.get('goal'),action:p.get('action'),owner:p.get('owner'),deadline:p.get('deadline'),indicator:p.get('indicator'),status:'Planejado'});closeModal();save();go('pdi')}});document.addEventListener('change',function(e){if(e.target.getAttribute('data-pdi')){var p=db.pdi.find(function(x){return x.id===e.target.getAttribute('data-pdi')});if(p){p.status=e.target.value;save()}}if(e.target.id==='evalCoordinator'){var c=db.coordinators.find(function(x){return x.id===e.target.value});if(c)$('#evalUnit').value=c.unit}if(e.target.id==='rankingPeriod')renderRanking();if(e.target.id==='dashPeriod'||e.target.id==='dashUnit')renderDashboard()});document.addEventListener('input',function(e){if(e.target.id==='rankingSearch')renderRanking()});renderCriteria();renderAll();go('dashboard')}
function exportData(){var a=document.createElement('a'),u=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.href=u;a.download='performance-security-dados.json';document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(u)},500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();})();